export interface Country {
  name: string;
  code: string;
  flag: string;
}

export const countries: Country[] = [
  { name: "Afghanistan", code: "AFG", flag: "https://flagcdn.com/w320/af.png" },
  { name: "Albania", code: "ALB", flag: "https://flagcdn.com/w320/al.png" },
  { name: "Algeria", code: "DZA", flag: "https://flagcdn.com/w320/dz.png" },
  { name: "Andorra", code: "AND", flag: "https://flagcdn.com/w320/ad.png" },
  { name: "Angola", code: "AGO", flag: "https://flagcdn.com/w320/ao.png" },
  { name: "Antigua and Barbuda", code: "ATG", flag: "https://flagcdn.com/w320/ag.png" },
  { name: "Argentina", code: "ARG", flag: "https://flagcdn.com/w320/ar.png" },
  { name: "Armenia", code: "ARM", flag: "https://flagcdn.com/w320/am.png" },
  { name: "Australia", code: "AUS", flag: "https://flagcdn.com/w320/au.png" },
  { name: "Austria", code: "AUT", flag: "https://flagcdn.com/w320/at.png" },
  { name: "Azerbaijan", code: "AZE", flag: "https://flagcdn.com/w320/az.png" },
  { name: "Bahamas", code: "BHS", flag: "https://flagcdn.com/w320/bs.png" },
  { name: "Bahrain", code: "BHR", flag: "https://flagcdn.com/w320/bh.png" },
  { name: "Bangladesh", code: "BGD", flag: "https://flagcdn.com/w320/bd.png" },
  { name: "Barbados", code: "BRB", flag: "https://flagcdn.com/w320/bb.png" },
  { name: "Belarus", code: "BLR", flag: "https://flagcdn.com/w320/by.png" },
  { name: "Belgium", code: "BEL", flag: "https://flagcdn.com/w320/be.png" },
  { name: "Belize", code: "BLZ", flag: "https://flagcdn.com/w320/bz.png" },
  { name: "Benin", code: "BEN", flag: "https://flagcdn.com/w320/bj.png" },
  { name: "Bhutan", code: "BTN", flag: "https://flagcdn.com/w320/bt.png" },
  { name: "Bolivia", code: "BOL", flag: "https://flagcdn.com/w320/bo.png" },
  { name: "Bosnia and Herzegovina", code: "BIH", flag: "https://flagcdn.com/w320/ba.png" },
  { name: "Botswana", code: "BWA", flag: "https://flagcdn.com/w320/bw.png" },
  { name: "Brazil", code: "BRA", flag: "https://flagcdn.com/w320/br.png" },
  { name: "Brunei", code: "BRN", flag: "https://flagcdn.com/w320/bn.png" },
  { name: "Bulgaria", code: "BGR", flag: "https://flagcdn.com/w320/bg.png" },
  { name: "Burkina Faso", code: "BFA", flag: "https://flagcdn.com/w320/bf.png" },
  { name: "Burundi", code: "BDI", flag: "https://flagcdn.com/w320/bi.png" },
  { name: "Cabo Verde", code: "CPV", flag: "https://flagcdn.com/w320/cv.png" },
  { name: "Cambodia", code: "KHM", flag: "https://flagcdn.com/w320/kh.png" },
  { name: "Cameroon", code: "CMR", flag: "https://flagcdn.com/w320/cm.png" },
  { name: "Canada", code: "CAN", flag: "https://flagcdn.com/w320/ca.png" },
  { name: "Central African Republic", code: "CAF", flag: "https://flagcdn.com/w320/cf.png" },
  { name: "Chad", code: "TCD", flag: "https://flagcdn.com/w320/td.png" },
  { name: "Chile", code: "CHL", flag: "https://flagcdn.com/w320/cl.png" },
  { name: "China", code: "CHN", flag: "https://flagcdn.com/w320/cn.png" },
  { name: "Colombia", code: "COL", flag: "https://flagcdn.com/w320/co.png" },
  { name: "Comoros", code: "COM", flag: "https://flagcdn.com/w320/km.png" },
  { name: "Congo (Congo-Brazzaville)", code: "COG", flag: "https://flagcdn.com/w320/cg.png" },
  { name: "Costa Rica", code: "CRI", flag: "https://flagcdn.com/w320/cr.png" },
  { name: "Croatia", code: "HRV", flag: "https://flagcdn.com/w320/hr.png" },
  { name: "Cuba", code: "CUB", flag: "https://flagcdn.com/w320/cu.png" },
  { name: "Cyprus", code: "CYP", flag: "https://flagcdn.com/w320/cy.png" },
  { name: "Czech Republic", code: "CZE", flag: "https://flagcdn.com/w320/cz.png" },
  { name: "Democratic Republic of the Congo", code: "COD", flag: "https://flagcdn.com/w320/cd.png" },
  { name: "Denmark", code: "DNK", flag: "https://flagcdn.com/w320/dk.png" },
  { name: "Djibouti", code: "DJI", flag: "https://flagcdn.com/w320/dj.png" },
  { name: "Dominica", code: "DMA", flag: "https://flagcdn.com/w320/dm.png" },
  { name: "Dominican Republic", code: "DOM", flag: "https://flagcdn.com/w320/do.png" },
  { name: "Ecuador", code: "ECU", flag: "https://flagcdn.com/w320/ec.png" },
  { name: "Egypt", code: "EGY", flag: "https://flagcdn.com/w320/eg.png" },
  { name: "El Salvador", code: "SLV", flag: "https://flagcdn.com/w320/sv.png" },
  { name: "Equatorial Guinea", code: "GNQ", flag: "https://flagcdn.com/w320/gq.png" },
  { name: "Eritrea", code: "ERI", flag: "https://flagcdn.com/w320/er.png" },
  { name: "Estonia", code: "EST", flag: "https://flagcdn.com/w320/ee.png" },
  { name: "Ethiopia", code: "ETH", flag: "https://flagcdn.com/w320/et.png" },
  { name: "Fiji", code: "FJI", flag: "https://flagcdn.com/w320/fj.png" },
  { name: "Finland", code: "FIN", flag: "https://flagcdn.com/w320/fi.png" },
  { name: "France", code: "FRA", flag: "https://flagcdn.com/w320/fr.png" },
  { name: "Gabon", code: "GAB", flag: "https://flagcdn.com/w320/ga.png" },
  { name: "Gambia", code: "GMB", flag: "https://flagcdn.com/w320/gm.png" },
  { name: "Georgia", code: "GEO", flag: "https://flagcdn.com/w320/ge.png" },
  { name: "Germany", code: "DEU", flag: "https://flagcdn.com/w320/de.png" },
  { name: "Ghana", code: "GHA", flag: "https://flagcdn.com/w320/gh.png" },
  { name: "Greece", code: "GRC", flag: "https://flagcdn.com/w320/gr.png" },
  { name: "Grenada", code: "GRD", flag: "https://flagcdn.com/w320/gd.png" },
  { name: "Guatemala", code: "GTM", flag: "https://flagcdn.com/w320/gt.png" },
  { name: "Guinea", code: "GIN", flag: "https://flagcdn.com/w320/gn.png" },
  { name: "Guinea-Bissau", code: "GNB", flag: "https://flagcdn.com/w320/gw.png" },
  { name: "Guyana", code: "GUY", flag: "https://flagcdn.com/w320/gy.png" },
  { name: "Haiti", code: "HTI", flag: "https://flagcdn.com/w320/ht.png" },
  { name: "Honduras", code: "HND", flag: "https://flagcdn.com/w320/hn.png" },
  { name: "Hungary", code: "HUN", flag: "https://flagcdn.com/w320/hu.png" },
  { name: "Iceland", code: "ISL", flag: "https://flagcdn.com/w320/is.png" },
  { name: "India", code: "IND", flag: "https://flagcdn.com/w320/in.png" },
  { name: "Indonesia", code: "IDN", flag: "https://flagcdn.com/w320/id.png" },
  { name: "Iran", code: "IRN", flag: "https://flagcdn.com/w320/ir.png" },
  { name: "Iraq", code: "IRQ", flag: "https://flagcdn.com/w320/iq.png" },
  { name: "Ireland", code: "IRL", flag: "https://flagcdn.com/w320/ie.png" },
  { name: "Israel", code: "ISR", flag: "https://flagcdn.com/w320/il.png" },
  { name: "Italy", code: "ITA", flag: "https://flagcdn.com/w320/it.png" },
  { name: "Jamaica", code: "JAM", flag: "https://flagcdn.com/w320/jm.png" },
  { name: "Japan", code: "JPN", flag: "https://flagcdn.com/w320/jp.png" },
  { name: "Jordan", code: "JOR", flag: "https://flagcdn.com/w320/jo.png" },
  { name: "Kazakhstan", code: "KAZ", flag: "https://flagcdn.com/w320/kz.png" },
  { name: "Kenya", code: "KEN", flag: "https://flagcdn.com/w320/ke.png" },
  { name: "Kiribati", code: "KIR", flag: "https://flagcdn.com/w320/ki.png" },
  { name: "Kuwait", code: "KWT", flag: "https://flagcdn.com/w320/kw.png" },
  { name: "Kyrgyzstan", code: "KGZ", flag: "https://flagcdn.com/w320/kg.png" },
  { name: "Laos", code: "LAO", flag: "https://flagcdn.com/w320/la.png" },
  { name: "Latvia", code: "LVA", flag: "https://flagcdn.com/w320/lv.png" },
  { name: "Lebanon", code: "LBN", flag: "https://flagcdn.com/w320/lb.png" },
  { name: "Lesotho", code: "LSO", flag: "https://flagcdn.com/w320/ls.png" },
  { name: "Liberia", code: "LBR", flag: "https://flagcdn.com/w320/lr.png" },
  { name: "Libya", code: "LBY", flag: "https://flagcdn.com/w320/ly.png" },
  { name: "Liechtenstein", code: "LIE", flag: "https://flagcdn.com/w320/li.png" },
  { name: "Lithuania", code: "LTU", flag: "https://flagcdn.com/w320/lt.png" },
  { name: "Luxembourg", code: "LUX", flag: "https://flagcdn.com/w320/lu.png" },
  { name: "Madagascar", code: "MDG", flag: "https://flagcdn.com/w320/mg.png" },
  { name: "Malawi", code: "MWI", flag: "https://flagcdn.com/w320/mw.png" },
  { name: "Malaysia", code: "MYS", flag: "https://flagcdn.com/w320/my.png" },
  { name: "Maldives", code: "MDV", flag: "https://flagcdn.com/w320/mv.png" },
  { name: "Mali", code: "MLI", flag: "https://flagcdn.com/w320/ml.png" },
  { name: "Malta", code: "MLT", flag: "https://flagcdn.com/w320/mt.png" },
  { name: "Marshall Islands", code: "MHL", flag: "https://flagcdn.com/w320/mh.png" },
  { name: "Mauritania", code: "MRT", flag: "https://flagcdn.com/w320/mr.png" },
  { name: "Mauritius", code: "MUS", flag: "https://flagcdn.com/w320/mu.png" },
  { name: "Mexico", code: "MEX", flag: "https://flagcdn.com/w320/mx.png" },
  { name: "Micronesia", code: "FSM", flag: "https://flagcdn.com/w320/fm.png" },
  { name: "Moldova", code: "MDA", flag: "https://flagcdn.com/w320/md.png" },
  { name: "Monaco", code: "MCO", flag: "https://flagcdn.com/w320/mc.png" },
  { name: "Mongolia", code: "MNG", flag: "https://flagcdn.com/w320/mn.png" },
  { name: "Montenegro", code: "MNE", flag: "https://flagcdn.com/w320/me.png" },
  { name: "Morocco", code: "MAR", flag: "https://flagcdn.com/w320/ma.png" },
  { name: "Mozambique", code: "MOZ", flag: "https://flagcdn.com/w320/mz.png" },
  { name: "Myanmar", code: "MMR", flag: "https://flagcdn.com/w320/mm.png" },
  { name: "Namibia", code: "NAM", flag: "https://flagcdn.com/w320/na.png" },
  { name: "Nauru", code: "NRU", flag: "https://flagcdn.com/w320/nr.png" },
  { name: "Nepal", code: "NPL", flag: "https://flagcdn.com/w320/np.png" },
  { name: "Netherlands", code: "NLD", flag: "https://flagcdn.com/w320/nl.png" },
  { name: "New Zealand", code: "NZL", flag: "https://flagcdn.com/w320/nz.png" },
  { name: "Nicaragua", code: "NIC", flag: "https://flagcdn.com/w320/ni.png" },
  { name: "Niger", code: "NER", flag: "https://flagcdn.com/w320/ne.png" },
  { name: "Nigeria", code: "NGA", flag: "https://flagcdn.com/w320/ng.png" },
  { name: "North Korea", code: "PRK", flag: "https://flagcdn.com/w320/kp.png" },
  { name: "North Macedonia", code: "MKD", flag: "https://flagcdn.com/w320/mk.png" },
  { name: "Norway", code: "NOR", flag: "https://flagcdn.com/w320/no.png" },
  { name: "Oman", code: "OMN", flag: "https://flagcdn.com/w320/om.png" },
  { name: "Pakistan", code: "PAK", flag: "https://flagcdn.com/w320/pk.png" },
  { name: "Palau", code: "PLW", flag: "https://flagcdn.com/w320/pw.png" },
  { name: "Panama", code: "PAN", flag: "https://flagcdn.com/w320/pa.png" },
  { name: "Papua New Guinea", code: "PNG", flag: "https://flagcdn.com/w320/pg.png" },
  { name: "Paraguay", code: "PRY", flag: "https://flagcdn.com/w320/py.png" },
  { name: "Peru", code: "PER", flag: "https://flagcdn.com/w320/pe.png" },
  { name: "Philippines", code: "PHL", flag: "https://flagcdn.com/w320/ph.png" },
  { name: "Poland", code: "POL", flag: "https://flagcdn.com/w320/pl.png" },
  { name: "Portugal", code: "PRT", flag: "https://flagcdn.com/w320/pt.png" },
  { name: "Qatar", code: "QAT", flag: "https://flagcdn.com/w320/qa.png" },
  { name: "Romania", code: "ROU", flag: "https://flagcdn.com/w320/ro.png" },
  { name: "Russia", code: "RUS", flag: "https://flagcdn.com/w320/ru.png" },
  { name: "Rwanda", code: "RWA", flag: "https://flagcdn.com/w320/rw.png" },
  { name: "Saint Kitts and Nevis", code: "KNA", flag: "https://flagcdn.com/w320/kn.png" },
  { name: "Saint Lucia", code: "LCA", flag: "https://flagcdn.com/w320/lc.png" },
  { name: "Saint Vincent and the Grenadines", code: "VCT", flag: "https://flagcdn.com/w320/vc.png" },
  { name: "Samoa", code: "WSM", flag: "https://flagcdn.com/w320/ws.png" },
  { name: "San Marino", code: "SMR", flag: "https://flagcdn.com/w320/sm.png" },
  { name: "Sao Tome and Principe", code: "STP", flag: "https://flagcdn.com/w320/st.png" },
  { name: "Saudi Arabia", code: "SAU", flag: "https://flagcdn.com/w320/sa.png" },
  { name: "Senegal", code: "SEN", flag: "https://flagcdn.com/w320/sn.png" },
  { name: "Serbia", code: "SRB", flag: "https://flagcdn.com/w320/rs.png" },
  { name: "Seychelles", code: "SYC", flag: "https://flagcdn.com/w320/sc.png" },
  { name: "Sierra Leone", code: "SLE", flag: "https://flagcdn.com/w320/sl.png" },
  { name: "Singapore", code: "SGP", flag: "https://flagcdn.com/w320/sg.png" },
  { name: "Slovakia", code: "SVK", flag: "https://flagcdn.com/w320/sk.png" },
  { name: "Slovenia", code: "SVN", flag: "https://flagcdn.com/w320/si.png" },
  { name: "Solomon Islands", code: "SLB", flag: "https://flagcdn.com/w320/sb.png" },
  { name: "Somalia", code: "SOM", flag: "https://flagcdn.com/w320/so.png" },
  { name: "South Africa", code: "ZAF", flag: "https://flagcdn.com/w320/za.png" },
  { name: "South Korea", code: "KOR", flag: "https://flagcdn.com/w320/kr.png" },
  { name: "South Sudan", code: "SSD", flag: "https://flagcdn.com/w320/ss.png" },
  { name: "Spain", code: "ESP", flag: "https://flagcdn.com/w320/es.png" },
  { name: "Sri Lanka", code: "LKA", flag: "https://flagcdn.com/w320/lk.png" },
  { name: "Sudan", code: "SDN", flag: "https://flagcdn.com/w320/sd.png" },
  { name: "Suriname", code: "SUR", flag: "https://flagcdn.com/w320/sr.png" },
  { name: "Sweden", code: "SWE", flag: "https://flagcdn.com/w320/se.png" },
  { name: "Switzerland", code: "CHE", flag: "https://flagcdn.com/w320/ch.png" },
  { name: "Syria", code: "SYR", flag: "https://flagcdn.com/w320/sy.png" },
  { name: "Taiwan", code: "TWN", flag: "https://flagcdn.com/w320/tw.png" },
  { name: "Tajikistan", code: "TJK", flag: "https://flagcdn.com/w320/tj.png" },
  { name: "Tanzania", code: "TZA", flag: "https://flagcdn.com/w320/tz.png" },
  { name: "Thailand", code: "THA", flag: "https://flagcdn.com/w320/th.png" },
  { name: "Timor-Leste", code: "TLS", flag: "https://flagcdn.com/w320/tl.png" },
  { name: "Togo", code: "TGO", flag: "https://flagcdn.com/w320/tg.png" },
  { name: "Tonga", code: "TON", flag: "https://flagcdn.com/w320/to.png" },
  { name: "Trinidad and Tobago", code: "TTO", flag: "https://flagcdn.com/w320/tt.png" },
  { name: "Tunisia", code: "TUN", flag: "https://flagcdn.com/w320/tn.png" },
  { name: "Turkey", code: "TUR", flag: "https://flagcdn.com/w320/tr.png" },
  { name: "Turkmenistan", code: "TKM", flag: "https://flagcdn.com/w320/tm.png" },
  { name: "Tuvalu", code: "TUV", flag: "https://flagcdn.com/w320/tv.png" },
  { name: "Uganda", code: "UGA", flag: "https://flagcdn.com/w320/ug.png" },
  { name: "Ukraine", code: "UKR", flag: "https://flagcdn.com/w320/ua.png" },
  { name: "United Arab Emirates", code: "ARE", flag: "https://flagcdn.com/w320/ae.png" },
  { name: "United Kingdom", code: "GBR", flag: "https://flagcdn.com/w320/gb.png" },
  { name: "United States", code: "USA", flag: "https://flagcdn.com/w320/us.png" },
  { name: "Uruguay", code: "URY", flag: "https://flagcdn.com/w320/uy.png" },
  { name: "Uzbekistan", code: "UZB", flag: "https://flagcdn.com/w320/uz.png" },
  { name: "Vanuatu", code: "VUT", flag: "https://flagcdn.com/w320/vu.png" },
  { name: "Venezuela", code: "VEN", flag: "https://flagcdn.com/w320/ve.png" },
  { name: "Vietnam", code: "VNM", flag: "https://flagcdn.com/w320/vn.png" },
  { name: "Yemen", code: "YEM", flag: "https://flagcdn.com/w320/ye.png" },
  { name: "Zambia", code: "ZMB", flag: "https://flagcdn.com/w320/zm.png" },
  { name: "Zimbabwe", code: "ZWE", flag: "https://flagcdn.com/w320/zw.png" },
];
